package:
  format-version: "1.0.0"
  name: "bootloader_apps_pic32cm_jh00_jh01"
  version: "3.1.0"
  type: "application"
  status: "production"
  required: true

  dependencies:
    - name: "bootloader"
      type: "package"
      version: "dev"


